### ISSUE TITLE
About transplantation

### ISSUE THREAD

**Issue by Maple-Mo** [miyucomics/hexcellular#4]
I have experienced Hexcellular in fabric, and I feel it is very useful. Do you plan to transplant it to forge?
My archives and games are hard to leave forge...

**Comment by miyucomics** [comment]
Sorry, I will not be moving any of my addons to Forge due to the increased work I would need to do to support two modloaders, the ease and speed of development of Fabric, and the various controversies surrounding the Forge modloader.
